POST {{baseUrl}}/users
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "name": "guest user",
    "plan": "guest"
}

###

GET {{baseUrl}}/users/me
Authorization: Bearer {{$dotenv TOKEN}}
